# Copyright (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_call:
    inputs:
      rebuild-all:
        description: 'Whether to force rebuild all components'
        type: boolean
        default: false
        required: false

permissions:
  contents: read

jobs:
  check-changes:
    name: "Checking for changes"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      collaborative-slam-changed: ${{ steps.filter.outputs.collaborative-slam-location || inputs.rebuild-all }}
      fast-mapping-changed: ${{ steps.filter.outputs.fast-mapping-location || inputs.rebuild-all }}
      groundfloor-changed: ${{ steps.filter.outputs.groundfloor-location || inputs.rebuild-all }}
      its-planner-changed: ${{ steps.filter.outputs.its-planner-location || inputs.rebuild-all }}
      multicam-demo-changed: ${{ steps.filter.outputs.multicam-demo-location || inputs.rebuild-all }}
      object-detection-changed: ${{ steps.filter.outputs.object-detection-location || inputs.rebuild-all }}
      simulations-changed: ${{ steps.filter.outputs.simulations-location || inputs.rebuild-all }}
      wandering-changed: ${{ steps.filter.outputs.wandering-location || inputs.rebuild-all }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: false
          sparse-checkout: robotics-ai-suite/components
      - name: Configure paths to look for changes
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        with:
          filters: |
            collaborative-slam-location:
              - 'robotics-ai-suite/components/collaborative-slam/**'
            fast-mapping-location:
              - 'robotics-ai-suite/components/fast-mapping/**'
            groundfloor-location:
              - 'robotics-ai-suite/components/groundfloor/**'
            its-planner-location:
              - 'robotics-ai-suite/components/its-planner/**'
            multicam-demo-location:
              - 'robotics-ai-suite/components/multicam-demo/**'
            object-detection-location:
              - 'robotics-ai-suite/components/object-detection/**'
            simulations-location:
              - 'robotics-ai-suite/components/simulations/**'
            wandering-location:
              - 'robotics-ai-suite/components/wandering/**'

  collaborative-slam:
    name: "Collaborative SLAM"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.collaborative-slam-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-collaborative-slam.yaml"

  fast-mapping:
    name: "Fast Mapping"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.fast-mapping-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-fast-mapping.yaml"

  groundfloor:
    name: "Groundfloor"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.groundfloor-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-groundfloor.yaml"

  its-planner:
    name: "ITS Planner"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.its-planner-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-its-planner.yaml"

  multicam-demo:
    name: "Multi-Camera Demo"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.multicam-demo-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-multicam-demo.yaml"

  object-detection:
    name: "Object Detection"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.object-detection-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-object-detection.yaml"

  simulations:
    name: "Simulations"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.simulations-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-simulations.yaml"

  wandering:
    name: "Wandering"
    needs: check-changes
    if: ${{ needs.check-changes.outputs.wandering-changed == 'true' }}
    uses: "./.github/workflows/robotics-components-wandering.yaml"
